name: Publish Package to npmjs
on: pull_request

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: '18'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test
      - run: yarn build:release
      - run: npm version --no-git-tag-version 0.0.`date +%s`-pr-${PR_NUMBER}-dev
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
