name: ts-functional-iterator - Test build
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
          cache: 'yarn'
      - uses: actions/cache@v3
        id: cached-dependencies
        with:
          path: |
            **/node_modules
            .yarn/cache/**
            .yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test
      - run: yarn build
